### ISSUE TITLE
Snapshot id came as Number

### ISSUE THREAD

**Issue by yigitozkavci** [inzva/DigitalOcean.hs#3]
Error in $.droplets[0]['snapshot_ids'][0]: expected String, encountered Number"}

**Comment by wildsebastian** [comment]
Can you give me a bit more information please.
I tried `getSnapshot` and `getSnapshots` but it works.
Might be that DO fixed that. 🙂

**Comment by yigitozkavci** [comment]
Oh, I remember filing a bug report for this cause, and it might be the case that they fixed it. I will take a look at the endpoints :)

**Comment by yigitozkavci** [comment]
Now that I also tested it, it looks like they indeed fixed the problem. Thank you for the information @wildsebastian

**Comment by wildsebastian** [comment]
Cool! You are welcome!
